all:
	javac -d ../classes/ -cp ../classes/ EmptyDequeException.java
	javac -d ../classes/ -cp ../classes/ DequeInterface.java
	javac -d ../classes/ -cp ../classes/ ArrayDeque.java
	javac -d ../classes/ -cp ../classes/ ArrayDequeTester.java
	java -cp ../classes/ ArrayDequeTester

clean:
	rm ../classes/EmptyDequeException.class ../classes/DequeInterface.class ../classes/ArrayDeque.class ../classes/ArrayDequeTester.class
